stages:
  - test

variables:
  POSTGRES_PASSWORD: omq
  OMQ_DB_TYPE: pgsql
  SFTP_HOST: local-sftp
  SFTP_DIR: sftp_root
  SFTP_USER: foo
  SFTP_PASS: pass
  TZ: Europe/Prague

default:
  image: $CI_REGISTRY/infrastructure/qorus-test-base/qorus-test-base:develop
  before_script:
    - export QORUS_LOG_DIR="`pwd`/log"
    - $WORKDIR/qorus/test/docker_test/get_external_apps.sh
    - test/docker/setup.sh
    - $WORKDIR/qorus/test/docker_test/init.sh
    - "gosu qorus:qorus echo qorus.dataprovider-modules: `ls modules/|sed s/.qm/,/g` ExcelDataProvider >> $OMQ_DIR/etc/options"
    - gosu qorus:qorus $WORKDIR/qorus/test/docker_test/launch_qorus.sh

# --------------------------------
all-tests:
  stage: test
  tags:
    - docker-exec
  services:
    - name: atmoz/sftp:alpine
      command: ["foo:pass:::sftp_root"]
      alias: local-sftp
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - log
    when: on_failure
    expire_in: 2 days
  script:
    - gosu qorus:qorus make load-bb-tests
    - gosu qorus:qorus qctl restart
    - gosu qorus:qorus test/docker/test.sh
    - test/docker/cleanup.sh

# --------------------------------
#mailer-workflow-module:
#  stage: test
#  tags:
#    - docker-exec
#  services:
#    - name: postgres:11
#    - name: digiplant/fake-smtp
#      alias: fake_smtp
#  script:
#    - cp -rf MailerWorkflowModule $OMQ_DIR/user/modules
#    - gosu qorus:qorus oload -Rlv tests/MailerWorkflowModule/*.q*
#    - gosu qorus:qorus qore tests/MailerWorkflowModule/MailerWorkflowModule.qtest -vv
