# Release to master pull request
name: "Release building-blocks"
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/qorus/qorus-ce:latest
    env:
      OMQ_DB_NAME: postgres
      OMQ_DB_TYPE: pgsql
      OMQ_DB_HOST: postgres
      OMQ_DB_USER: postgres
      OMQ_DB_PASS: omq
      SFTP_HOST: local-sftp
      SFTP_DIR: sftp_root
      SFTP_USER: foo
      SFTP_PASS: pass
      TZ: Europe/Prague
      WORKDIR: /opt/qorus
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: omq
          PGTZ: Europe/Prague
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      sftp:
        image: atmoz/sftp:alpine
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install Docker and Wget
        run: |
          apt-get update
          apt-get install ca-certificates curl gnupg lsb-release wget -y
      - name: Setup environment
        run: |
          bash ./test/docker/setup.sh
      - name: Build and test
        run: |
          . /opt/qorus/bin/env.sh
          apt-get update
          apt-get install -y make
          make load-bb-tests -f Makefile
          . ./test/docker/test.sh
