# Release to master
name: "Release building-blocks"
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: https://git.qoretechnologies.com/infrastructure/qore-test-base/-/blob/develop/prep-ubuntu.sh
    env:
      POSTGRES_PASSWORD: omq
      OMQ_DB_NAME: postgres
      OMQ_DB_TYPE: pgsql
      OMQ_DB_HOST: postgres
      OMQ_DB_USER: postgres
      OMQ_DB_PASS: omq
      SFTP_HOST: local-sftp
      SFTP_DIR: sftp_root
      SFTP_USER: foo
      SFTP_PASS: pass
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: omq
          OMQ_DB_NAME: postgres
          OMQ_DB_TYPE: pgsql
          OMQ_DB_HOST: postgres
          OMQ_DB_USER: postgres
          OMQ_DB_PASS: omq
        ports:
          - 5432:5432
      sftp:
        image: atmoz/sftp:alpine
        env:
          SFTP_USER: foo
          SFTP_PASS: pass
        ports:
          - 2222:22
    steps:
      - name: Build and test
        run: |
          gosu qorus:qorus make load-all
          gosu qorus:qorus make test
