# Release to master pull request
name: "Release building-blocks"
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/qorus/qorus-ce:latest
    env:
      POSTGRES_PASSWORD: omq
      OMQ_DB_NAME: postgres
      OMQ_DB_TYPE: pgsql
      OMQ_DB_HOST: postgres
      OMQ_DB_USER: postgres
      OMQ_DB_PASS: omq
      SFTP_HOST: local-sftp
      SFTP_DIR: sftp_root
      SFTP_USER: foo
      SFTP_PASS: pass
      QORUS_ALLOW_ROOT: 1
      OMQ_DIR: /opt/qorus
      QORUS_INIT_STATE_DIR: ${OMQ_DIR}/init
      QORUS_INSTALL_PREFIX: /opt
      QORE_INCLUDE_DIR: ${OMQ_DIR}/qlib
      QORE_MODULE_DIR: ${OMQ_DIR}/qlib:${OMQ_DIR}/user/modules
      QORE_DATA_PROVIDERS: QorusDataProviders
      QORE_CONNECTION_PROVIDERS: QorusConnectionProvider
      QORE_DATASOURCE_PROVIDERS: QorusDatasourceProvider
      QORE_FILE_LOCATION_HANDLERS: QorusResourceFileLocationHandler
      ORACLE_INSTANT_CLIENT: /usr/lib/oracle
      ORACLE_HOME: ${ORACLE_INSTANT_CLIENT}
      TNS_ADMIN: ${ORACLE_INSTANT_CLIENT}
      PYTHONPATH: ${OMQ_DIR}/python:${OMQ_DIR}/user/python/lib/python3.10/site-packages
      PATH: ${QORUS_INSTALL_PREFIX}/bin:${OMQ_DIR}/bin:$PATH
      FREETDSCONF: $OMQ_DIR/etc/freetds.conf
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: omq
          OMQ_DB_NAME: postgres
          OMQ_DB_TYPE: pgsql
          OMQ_DB_HOST: postgres
          OMQ_DB_USER: postgres
          OMQ_DB_PASS: omq
        ports:
          - 5432:5432
      sftp:
        image: atmoz/sftp:alpine
        env:
          SFTP_USER: foo
          SFTP_PASS: pass
        ports:
          - 2222:22
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          apt-get update
          apt install make -y
          pwd
          ls -l
          make load-all -f Makefile
          make test -f Makefile
