# Release to master pull request
name: "Release building-blocks"
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/qorus/qorus-ce:latest
    env:
      OMQ_DB_NAME: postgres
      OMQ_DB_TYPE: pgsql
      OMQ_DB_HOST: postgres
      OMQ_DB_USER: postgres
      OMQ_DB_PASS: omq
      WORKDIR: /opt/qorus
      QORUS_SRC_DIR: .
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: omq
        ports:
          - 5432:5432
      sftp:
        image: atmoz/sftp:alpine
        env:
          SFTP_HOST: local-sftp
          SFTP_DIR: sftp_root
          SFTP_USER: foo
          SFTP_PASS: pass
        ports:
          - 2222:22
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install Docker and Wget
        run: |
          apt-get update
          apt-get install ca-certificates curl gnupg lsb-release wget -y
          mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
          docker run hello-world
      - name: Setup environment
        run: |
          . /opt/qorus/bin/env.sh
      - name: Run initial scripts
        run: |
          docker ps
          docker container ls
          . ./test/docker/setup.sh
          . ./test/docker_test/init.sh
          . ./test/docker_test/launch_qorus.sh
          apt-get update
          apt install make -y
      - name: Build and test
        run: |
          make load-all -f Makefile
          make test -f Makefile
